### ISSUE TITLE
rpc返回结果用Stream.collect(Collectors.toList())可以正常返回，用Stream.toList()返回会报错

### ISSUE THREAD

**Issue by baixiang0101** [apache/dubbo-hessian-lite#67]
rpc返回结果用Stream.collect(Collectors.toList())可以正常返回，用Stream.toList()返回会报错

```
Caused by: java.lang.UnsupportedOperationException: CollectionDeserializer[interface java.util.List]
at com.alibaba.com.caucho.hessian.io.AbstractDeserializer.readObject(AbstractDeserializer.java:127)
at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2848)
at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2175)
at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2104)
at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2148)
at com.alibaba.com.caucho.hessian.io.JavaDeserializer$ObjectListFieldDeserializer.deserialize(JavaDeserializer.java:528)
```

**Comment by AlbumenJ** [comment]
Please upgrade to 3.2.x and try use fastjson2 serialization.

**Comment by AlbumenJ** [comment]
Already fixed in https://github.com/apache/dubbo-hessian-lite/pull/71
